# Generated by Django 5.0.1 on 2025-12-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_enquiry_offer_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
