# Generated by Django 5.0.1 on 2025-12-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='image',
        ),
    ]
