# Generated by Django 5.0.1 on 2025-12-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='building_age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='pests',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='property_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='severity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='type',
            field=models.CharField(choices=[('contact', 'Contact Message'), ('enquiry', 'Enquiry')], default='enquiry', max_length=10),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='urgency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
