# Generated by Django 5.0.1 on 2025-12-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_enquiry_additional_info_enquiry_address_enquiry_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='service_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Service'), ('3-services', '3 Services (1 Year)'), ('6-services', '6 Services (2 Years)'), ('residential', 'Residential'), ('commercial', 'Commercial'), ('termite', 'Termite'), ('inspection', 'Inspection'), ('rodent', 'Rodent Control')], max_length=20, null=True),
        ),
    ]
