# Generated by Django 5.0.1 on 2025-12-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_alter_enquiry_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='package_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='quoted_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='property_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='service_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
