# Generated by Django 5.0.1 on 2025-12-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='display_location',
            field=models.CharField(choices=[('home', 'Home Page'), ('community', 'Community Page'), ('both', 'Both Pages')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
